apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - service.yaml
  - endpoints.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/instance: home-assistant
  app.kubernetes.io/name: home-assistant
