apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: apple-health-lake-ingress
  namespace: default
  annotations:
    cert-manager.io/issuer: "local-siemons-it-nl"
spec:
  tls:
    - hosts:
        - health-lake.local.siemons-it.nl
      secretName: local-siemons-it-nl-tls
  rules:
    - host: health-lake.local.siemons-it.nl
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: apple-health-lake
                port:
                  number: 80
