apiVersion: v1
kind: Service
metadata:
  name: apple-health-lake
  namespace: default
  labels:
    app.kubernetes.io/instance: apple-health-lake
    app.kubernetes.io/name: apple-health-lake
    app.kubernetes.io/component: ingester
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: apple-health-lake
    app.kubernetes.io/instance: apple-health-lake
    app.kubernetes.io/component: ingester
