apiVersion: v1
kind: Service
metadata:
  name: unifi-os-service
  namespace: unifi-os
  annotations:
    service.cilium.io/global: "true"
    service.cilium.io/shared: "true"
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.2.21
  selector:
    app: unifi-os-server
  ports:
    - name: webui
      port: 443
      targetPort: 443
      protocol: TCP
    - name: communication
      port: 8080
      targetPort: 8080
      protocol: TCP
    - name: network-app
      port: 8443
      targetPort: 8443
      protocol: TCP
    - name: hotspot-secure
      port: 8444
      targetPort: 8444
      protocol: TCP
    - name: hotspot-redir0
      port: 8880
      targetPort: 8880
      protocol: TCP
    - name: hotspot-redir1
      port: 8881
      targetPort: 8881
      protocol: TCP
    - name: hotspot-redir2
      port: 8882
      targetPort: 8882
      protocol: TCP
    - name: stun
      port: 3478
      targetPort: 3478
      protocol: UDP
    - name: rtp
      port: 5005
      targetPort: 5005
      protocol: TCP
    - name: syslog
      port: 5514
      targetPort: 5514
      protocol: UDP
    - name: aqmps
      port: 5671
      targetPort: 5671
      protocol: TCP
    - name: mobile-speed
      port: 6789
      targetPort: 6789
      protocol: TCP
    - name: id-hub
      port: 9543
      targetPort: 9543
      protocol: TCP
    - name: discovery
      port: 10003
      targetPort: 10003
      protocol: UDP
    - name: site-super
      port: 11084
      targetPort: 11084
      protocol: TCP
