apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cert-practice-ingress
  namespace: default
  annotations:
    cert-manager.io/issuer: "local-siemons-it-nl"
spec:
  tls:
    - hosts:
        - cert-practice.local.siemons-it.nl
      secretName: local-siemons-it-nl-tls
  rules:
    - host: cert-practice.local.siemons-it.nl
      http:
        paths:
          # API routes to backend
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: cert-practice-backend
                port:
                  number: 8000
          # Everything else to frontend
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cert-practice-frontend
                port:
                  number: 80
