apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - deployment-backend.yaml
  - deployment-frontend.yaml
  - service-backend.yaml
  - service-frontend.yaml
  - ingress.yaml
  - external-secret.yaml

commonLabels:
  app.kubernetes.io/instance: cert-practice
  app.kubernetes.io/name: cert-practice
