apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: clawdbot-ingress
  namespace: clawdbot
  annotations:
    cert-manager.io/cluster-issuer: local-siemons-it-nl
spec:
  ingressClassName: traefik
  rules:
    - host: clawdbot.local.siemons-it.nl
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: clawdbot-gateway
                port:
                  number: 18789
  tls:
    - hosts:
        - clawdbot.local.siemons-it.nl
      secretName: local-siemons-it-nl-tls
