apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: clawdbot
resources:
  - namespace.yaml
  - external-secret.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
